### ISSUE TITLE
No table contents  

### ISSUE THREAD

**Issue by bchain** [JuliaComputing/TableView.jl#48]
I am trying to use TableView (version 0.6.0) in Julia 1.4. Example code below. The table opens in Atom's plot panel, shows two columns called a and b, but displays no entries. I tried displaying with blink as well but still doesn't work. 

using (TableView)
a = randn(10)
b= randn(10) 
data = DataFrame(a=a,b=b)
showtable(data)

**Comment by JackRab** [comment]
Can you please try the following code?
```Julia
using Blink, TableView
w = Window(); body!(w, showtable(rand(10,10)));
```
What do you get?

**Comment by bchain** [comment]
An error message 
MethodError: no method matching eachcolumn(::Tables.MatrixRow{Array{Float64,2}})
Do you need the full stacktrace ?

**Comment by JackRab** [comment]
I am not a developer of this library. But I have just a [similar issue](https://github.com/JuliaComputing/TableView.jl/issues/47#issue-631821984) using this. The problem is solved using the latest version. It may be worth double-checking which version you are using now since 
```Julia
] add TableView
```
may not install the most recent version. To install the most recent version, you can do
```Julia
] add TableView#master
```

**Comment by bchain** [comment]
Still doesn't work sadly !!

**Comment by pfitzseb** [comment]
Can you try `pkg> add TableView@0.6.0`? If that doesn't resolve the error: What does 'pkg> status` print?

**Comment by bchain** [comment]
status prints version 0.6.0 #master

**Comment by bchain** [comment]
Now works !!!
